export const constants = {
  newRoom: "New room",
  createRoom: "Create room",
  create: "Create",
  join: "Join",
  charactersLeft: "Characters left",
  roomLoadingMessage: "Please wait, Your conversation is about to start...",
  roomTitle: "Room title",
  enterNewRoom: "Enter room title",
  shortDescription: "Short description",
  enterShortDescription: "Enter short description",
  peoplePickerLabel: "Invite your colleagues",
  peoplePickerPlaceholder: "Start typing a name",
  chooseRoomImage: "Choose room image",
  dashboardLoadingMessage: "Please wait, Loading your homepage",
  placeHolderImage: "https://thealmanian.com/wp-content/uploads/2019/01/product_image_thumbnail_placeholder.png",
  find: "Find room",
}